const quizzes = {
    "accounting1": {
        isChapters: true,
        chapters: [
            {
                id: "ch1",
                title: "Ch 1: Accounting in Action",
                description: "Nature of accounting, users, and ethics.",
                questions: [
                    { question: "Which of the following is *not* a step in the accounting process?", options: ["identification", "verification", "recording", "communication"], correct: 1 },
                    { question: "Financial accounting provides internal reports to help users make decisions about their companies.", options: ["True", "False"], correct: 1 },
                    { question: "Which of the following statements about users of accounting information is incorrect?", options: ["Management is an internal users", "Taxing authorities are external users", "Present creditors are external users", "Regulatory authorities are internal users"], correct: 3 },
                    { question: "Which of the following would not be considered an internal user of accounting data for a company?", options: ["president of the company", "controller of the company", "production manager", "internal Revenue Service"], correct: 3 },
                    { question: "Ethics are the standards of conduct by which one's actions are judged as", options: ["honest or dishonest", "right or wrong", "fair or unfair", "all of these"], correct: 3 },
                    { question: "The cost principle states that", options: ["assets should be initially recorded at cost and adjusted when the fair value changes", "activities of an entity are to be kept separate and distinct from its owner", "assets should be recorded at their cost", "only transaction data capable of being expressed in terms of money be included in the accounting records"], correct: 2 },
                    { question: "The three types of business entities are", options: ["proprietorships, small businesses, and partnerships", "proprietorships, partnerships, and corporations", "proprietorships, partnerships, and large businesses", "financial, manufacturing, and service companies"], correct: 1 },
                    { question: "At the beginning of the year, Kimball Company had total assets of $700,000 and total liabilities of $400,000. If the total assets increased $100,000 and the total liabilities decreased $80,000, what is the amount of owner's equity at the end of the year?", options: ["$300,000", "$480,000", "$20,000", "cannot be determined from the data given"], correct: 1 },
                    { question: "Performing services on account will have the following effects on the components of the basic accounting equation:", options: ["increase assets and decrease owner's equity", "increase assets and increase owner's equity", "increase assets and increase liabilities", "increase liabilities and increase owner's equity"], correct: 1 },
                    { question: "The statement of cash flows provides information on the cash receipts and payments for a specific period of time.", options: ["True", "False"], correct: 0 }
                ]
            },
            {
                id: "ch2",
                title: "Ch 2: The Recording Process",
                description: "Debits, credits, and the ledger.",
                questions: [
                    { question: "The accounting process is correctly sequenced as", options: ["identification, communication, recording", "recording, communication, identification.", "identification, recording, communication.", "communication, recording, identification."], correct: 2 },
                    { question: "The accounting process involves all of the following except", options: ["identifying economic transactions that are relevant to the business.", "communicating financial information to users by preparing financial reports.", "recording nonquantifiable economic events.", "analyzing and interpreting financial reports."], correct: 2 },
                    { question: "Which of the following would not be considered an external user of accounting data?", options: ["Internal Revenue Service Agent.", "Management.", "Creditors.", "Customers."], correct: 1 },
                    { question: "Which of the following would not be considered internal users of accounting data for a company?", options: ["The president of a company.", "The controller of a company.", "Creditors of a company.", "Salesmen of the company."], correct: 2 },
                    { question: "Jordan Company has five plants nationwide that cost a total of $100 million. The current fair value of the plants is $500 million. The plants will be recorded and reported as assets at", options: ["$100 million", "$600 million", "$400 million", "$500 million"], correct: 0 },
                    { question: "A small neighbourhood barbershop that is operated by its owner would likely be organized as a", options: ["joint venture.", "partnership.", "corporation.", "proprietorship."], correct: 3 },
                    { question: "The common characteristic possessed by all assets is", options: ["long life.", "great monetary value.", "tangible nature.", "future economic benefit."], correct: 3 },
                    { question: "The basic accounting equation may be expressed as", options: ["Assets = Equities.", "Assets – Liabilities = Owner's Equity.", "Assets = Liabilities + Owner's Equity.", "All of these answer choices are correct."], correct: 2 },
                    { question: "Liabilities of a company would not include", options: ["notes payable.", "accounts payable.", "salaries and wages payable.", "cash."], correct: 3 },
                    { question: "When an owner withdraws cash or other assets from a business for personal use, these withdrawals are termed", options: ["depletions.", "consumptions.", "drawings.", "credit line."], correct: 2 }
                ]
            }
        ]
    },
    "accounting2": {
        isChapters: true,
        chapters: [
            {
                id: "ch3",
                title: "Ch 3: Adjusting the Accounts",
                description: "Accruals, deferrals, and depreciation.",
                questions: [
                    { question: "*Amman Company had the following transactions during 2021*\n\nSales of $4,500 on account\nCollected $2,000 for services to be performed in 2022\nPaid $1,625 cash in salaries\nPurchased airline tickets for $250 in December for a trip to take place in 2022\n\n  *What is Amman’s 2021 net income using cash basis accounting? * ", options: ["$125", "$4,625", "$375", "$4,875"], correct: 0 },
                    { question: "Lake of Fire Company purchased supplies costing $7,000 and debited Supplies for the full amount. At the end of the accounting period, a physical count of supplies revealed $2,400 still on hand. \n\nThe appropriate *adjusting journal entry* to be made at the end of the period would be\n", options: ["Debit Supplies Expense, $4,600; Credit Supplies, $4,600", "Debit Supplies, $2,400; Credit Supplies Expense, $2,400", "Debit Supplies Expense, $2,400; Credit Supplies, $2,400", "Debit Supplies, $4,600; Credit Supplies Expense, $4,600"], correct: 0 },
                    { question: "If unearned revenues are initially recorded in revenue accounts and have not all been earned at the end of the accounting period, then failure to make an *adjusting entry* will cause", options: ["accounts receivable to be overstated", "revenues to be understated", "liabilities to be overstated", "revenues to be overstated"], correct: 2 },
                    { question: "A company shows a balance in Salaries and Wages Payable of $38,000 at the end of the month. The next payroll amounting to $45,000 is to be paid in the following month. \n\nWhat will be the (journal entry) to record the payment of salaries?", options: ["Dr. Salaries and Wages Expense 7,000  Cr. Cash 7,000", "Dr.  Salaries and Wages Expense 7,000  Dr. Salaries and Wages Payable 38,000  Cr. Cash 45,000", "Dr. Salaries and Wages Expense 45,000   Cr. Salaries and Wages Payable 45,000", "Dr. Salaries and Wages Expense 45,000   Cr.  Cash 45,000"], correct: 1 },
                    { question: "What is the proper adjusting entry at June 30, the end of the fiscal year, based on a prepaid insurance account balance before adjustment, $15,500, and *unexpired* amounts per analysis of policies of $6,000?", options: ["Debit Prepaid Insurance, $9,500; Credit Insurance Expense, $9,500", "Debit Insurance Expense, $15,500; Credit Prepaid Insurance, $15,500", "Debit Insurance Expense, $6,000; Credit Prepaid Insurance, $6,000", "Debit Insurance Expense, $9,500; Credit Prepaid Insurance, $9,500"], correct: 3 },
                    { question: "Under accrual-basis accounting  ", options: ["the ledger accounts must be adjusted to reflect a cash basis of accounting before financial statements are prepared under generally accepted accounting principles", "cash must be received before revenue is recognized", "net income is calculated by matching cash outflows against cash inflows", "events that change a company's financial statements are recognized in the period they occur rather than in the period in which cash is paid or received"], correct: 3 },
                    { question: "Carlos Lopes, an employee of Aveiro Corp., will not receive his paycheck until April 2. Based on services performed from March 15 to March 31, his salary was $1,000. The adjusting entry for Aveiro Corp. on March 31 is", options: ["Debit Salaries Expense 1,000 ; Credit Cash 1,000", "Debit Salaries Expense 1,000  ; Credit Salaries Payable 1,000 ", "Debit Salaries Payable 1,000 ; Credit Cash 1,000", "No entry is required"], correct: 1 },
                    { question: "The balance in the Prepaid Rent account before adjustment at the end of the year is $18,000, which represents three months’ rent paid on December1. The adjusting entry required on December 31 is to", options: ["Debit Rent Expense, $6,000; Credit Prepaid Rent, $6,000", "Debit Prepaid Rent, $12,000; Credit Rent Expense, $12,000", "Debit Rent Expense, $12,000; Credit Prepaid Rent $12,000", "Debit Prepaid Rent, $6,000; Credit Rent Expense, $6,000"], correct: 0 },
                    { question: "The adjusted trial balance is prepared", options: ["after financial statements are prepared", "after adjusting entries have been journalized and posted", "before the trial balance", "to prove the equality of total assets and total liabilities"], correct: 1 },
                    { question: "On *January 1, 2019*, Norina Inc. purchased equipment for $30,000. The company is depreciating the equipment at the rate of $500 per month. At *January 31*, 2020, the balance in Accumulated Depreciation is", options: ["$23,500", "$500", "$6,500", "$6,000"], correct: 2 },
                    { question: "Monthly and quarterly time periods are called", options: ["Fiscal periods", "Calendar periods", "Quarterly periods", "Interim periods"], correct: 3 },
                    { question: "On January 1, 2020, Nadia Company purchased a computer system for $5,670. The company expects to use the system for 3 years. The asset has no salvage value. The book value of the system at December 31, 2021 is", options: ["$1,890", "$3,780", "$5,670", "$0"], correct: 0 },
                    { question: "Adjusting entries are required", options: ["Quarterly", "Yearly", "Every time financial statements are prepared", "Monthly"], correct: 2 },
                    { question: "The revenue recognition principle dictates that revenue should be recognized in the accounting records", options: ["At the end of the month", "When cash is received", "When it is earned", "In the period that income taxes are paid"], correct: 2 },
                    { question: "Jacob Corporation issued a one-year, 9%, $300,000 note on April 30, 2012. Interest expense for the year ended December 31, 2012 was  ", options: ["$27,000", "$18,000", "$20,250", "$15,750"], correct: 1 },
                    { question: "Sakhr Corporation Investments purchased an 18-month insurance policy on May 31, 2019 for $3,240. The December 31, 2019 balance sheet would report Prepaid Insurance of", options: ["$1,260", "$1,980", "$0 because Prepaid Insurance is reported on the Income Statement", "$3,240"], correct: 1 },
                    { question: "At December 31, 2020, before any year-end adjustments, Mafraq Company's Insurance Expense account had a balance of $1,450 and its Prepaid Insurance account had a balance of $3,800. It was determined that $2,800 of the Prepaid Insurance had expired. The adjusted balance for Insurance Expense for the year would be", options: ["$2,450", "$1,450", "$4,250", "$2,800"], correct: 2 },
                    { question: "A law firm received $3,000 cash for legal services to be rendered in the future. The full amount was credited to the liability account Unearned Legal Fees. If the legal services have been rendered at the end of the accounting period and no adjusting entry is made, this would cause", options: ["Expenses to be overstated", "Liabilities to be understated", "Net income to be overstated", "Revenues to be understated"], correct: 3 },
                    { question: "An accounting time period that is one year in length, but does not begin on January 1, is referred to as", options: ["The time period assumption", "A reporting period", "A fiscal year", "An interim period"], correct: 2 },
                    { question: "Norina Youth Corporation purchased a one-year insurance policy in January 2012 for $82,500. The insurance policy is in effect from March 2012 through February 2013. If the company neglects to make the proper year-end adjustment for the expired insurance", options: ["Net income and assets will be overstated by $68,750", "Net income and assets will be understated by $68,750", "Net income and assets will be overstated by $13,750", "Net income and assets will be understated by $13,750"], correct: 0 }
                ]
            },
            {
                id: "ch6",
                title: "Ch 6: Inventories",
                description: "FIFO, LIFO, and Average Cost.",
                questions: [
                    { question: "A company just starting business made the following four inventory purchases in June:\n\nJune 1; 150 units $390\nJune 10; 200 units $585\nJune 15; 200 units $630\nJune 28; 150 units $510\n  *Total dollars $2,115*\n\n   A physical count of merchandise inventory on June 30 reveals that there are *200 units on\nhand*. Using the *FIFO inventory method*, the amount allocated to cost of goods sold for June is", options: ["$1,564", "$1,447", "$668", "$536"], correct: 0 },
                    { question: "Pappy’s Staff has the following inventory information\n\nJuly/1 , Beginning Inventory 10 units at $90\nJuly/5 , Purchases 60 units at $92\nJuly/14 , Sale 40 units\nJuly/20 , Purchases 30 units at $95\nJuly/30 , Sale 28 units\n\n  Assuming that a perpetual inventory system is used, what is the *ending inventory* on a\n*FIFO* basis?", options: ["$2,924", "$3,034", "$2,930", "$6,346"], correct: 1 },
                    { question: "A company just starting business made the following four inventory purchases in June:\n\nJune 1; 150 units $390\nJune 10; 200 units $585\nJune 15; 200 units $630\nJune 28; 150 units $510\n  *Total dollars $2,115*\n\n  A physical count of merchandise inventory on June 30 reveals that there are 200 units on\nhand. Using the *average-cost method*, the amount allocated to the ending inventory on June 30 is", options: ["$604", "$1,511", "$668", "$536"], correct: 0 },
                    { question: "Cost of goods sold is computed from the following equation:  ", options: ["sales – cost of goods purchased + beginning inventory – ending inventory", "beginning inventory – cost of goods purchased + ending inventory", "beginning inventory + cost of goods purchased – ending inventory", "sales + gross profit – ending inventory + beginning inventory"], correct: 2 },
                    { question: "Sakhr's Used Cars uses the *specific identification method* of costing inventory. During March, Sakhr purchased three cars for $6,000, $7,200, and $9,600, respectively. During March, two cars are sold for a total of $17,300. Sakhr determines that at March 31, the $7,200 car is still on hand. What is Sakhr’s gross profit for March?", options: ["$1,400", "$500", "$2,100", "$1,700"], correct: 3 },
                    { question: "At May 1, 2012, Kibbee Company had beginning inventory consisting of 100 units with a unit cost of $7. During May, the company purchased inventory as follows:\n\n   *400 units at $7*\n   *300 units at $8*\n\nThe company sold 500 units during the month for $12 per unit. Kibbee uses the average cost method. The value of Kibbee’s inventory at May 31, 2012 is  ", options: ["$3,750", "$1,500", "$2,212.5", "$2,250"], correct: 3 },
                    { question: "Days in inventory is calculated by dividing", options: ["365 days by average inventory", "365 days by the inventory turnover ratio", "Average inventory by 365 days", "The inventory turnover ratio by 365 days"], correct: 1 },
                    { question: "An error in the physical count of goods on hand at the end of a period resulted in a $15,000 overstatement of the ending inventory. The effect of this error in the current period is", options: ["Cost of Goods sold (Understated) /  Net Income (Understated)", "Cost of Goods sold (Overstated) / Net Income (Overstated)", "Cost of Goods sold (Overstated) / Net Income (Understated)", "Cost of Goods sold (Understated) / Net Income (Overstated)"], correct: 3 },
                    { question: "Beginning inventory plus the cost of goods purchased equals", options: ["Total goods purchased", "Cost of goods sold", "Cost of goods available for sale", "Net purchases"], correct: 2 },
                    { question: "Goods in transit should be included in the inventory of the buyer when the", options: ["Terms of sale are FOB destination", "Terms of sale are FOB shipping point", "Goods reach the buyer", "Public carrier accepts the goods from the seller"], correct: 1 },
                    { question: "A company just starting in business purchased three merchandise inventory items at the following prices. First purchase $80; Second purchase $95; Third purchase $85. If the company sold two units for a total of $250 and used FIFO costing, the gross profit for the period would be", options: ["$75", "$70", "$85", "$77"], correct: 0 },
                    { question: "A company purchased inventory as follows:\n\n   *150 units at $10*\n   *350 units at $12*\n\nThe *average unit cost* for inventory is", options: ["$11", "$12", "$11.4", "$10"], correct: 2 },
                    { question: "A company just starting business made the following four inventory purchases in June:\n\nJune 1; 150 units $390\nJune 10; 200 units $585\nJune 15; 200 units $630\nJune 28; 150 units $510\n  *Total dollars $2,115*\n\nA physical count of merchandise inventory on June 30 reveals that there are 200 units on\nhand. The inventory method which results in the highest gross profit for June is", options: ["The FIFO method", "Not determinable", "The LIFO method", "The weighted average unit cost method"], correct: 0 },
                    { question: "The following information was available for Pete Company at December 31, 2012: beginning inventory $90,000; ending inventory $70,000; cost of goods sold $656,000; and sales $900,000. Pete’s days in inventory in 2012 was", options: ["38.8 days", "44.5 days", "50 days", "32.3 days"], correct: 1 },
                    { question: "Jordan, Inc. has 5 computers which have been part of the inventory for over two years. Each computer cost $600 and originally retailed for $900. At the statement date, each computer has a current replacement cost of $400. *How much loss should Jordan, Inc., record for the year?*", options: ["$2,500", "$2,000", "$1,000", "$1,500"], correct: 2 }
                ]
            },
            {
                id: "ch7",
                title: "Ch 7: Fraud, Internal Control & Cash",
                description: "Bank reconciliation and cash controls.",
                questions: [
                    { question: "The cash account shows a balance of $45,000 before reconciliation. The bank statement does not include a deposit of $2,500 made on the last day of the month. The bank statement shows a collection by the bank of $1,200 and a customer’s check for $320 was returned because it was NSF. A customer’s check for $450 was recorded on the books as $540, and a check written for $69 was recorded as $96. The correct balance in the cash account was", options: ["$46,200", "$45,790", "$48,317", "$45,817"], correct: 3 },
                    { question: "A petty cash fund is generally established in order to", options: ["pay for all merchandise purchased on account", "make loans internally to employees", "pay relatively small expenditures", "pay employees’ wages"], correct: 2 },
                    { question: "A check returned by the bank marked \"NSF\" means", options: ["no service fee", "no signature found", "not satisfactorily filled-out", "not sufficient funds"], correct: 3 },
                    { question: "In preparing its bank reconciliation for the month of April 2012, Delano, Inc. has available the following information:\n\nBalance per bank statement, 4/30/12  $39,300\nNSF check returned with 4/30/12 bank statement $470\nDeposits in transit, 4/30/12 $5,000\nOutstanding checks, 4/30/12 $5,200\nBank service charges for April $30\n\n*What should be the adjusted cash balance at April 30, 2012?*", options: ["$39,010", "$38,630", "$38,800", "$39,100"], correct: 3 },
                    { question: "A bank reconciliation should be prepared", options: ["to explain any difference between the depositor's balance per books and the balance per bank", "by the person who is authorized to sign checks", "when an employee is suspected of fraud", "whenever the bank refuses to lend the company money"], correct: 0 },
                    { question: "If the month-end bank statement shows a balance of $24,000, outstanding checks are $18,000, a deposit of $5,000 was in transit at month end, and a check for $1,000 was erroneously charged by the bank against the account, the correct balance in the bank account at month end is", options: ["$12,000", "$24,000", "$11,000", "$38,000"], correct: 0 },
                    { question: "If a petty cash fund is established in the amount of $200, and contains $121 in cash and $84 in receipts for disbursements when it is replenished, the journal entry to record replenishment should include credits to the following accounts", options: ["Petty Cash, $84", "Petty Cash, $79", "Cash, $79; Cash Over and Short, $5", "Cash, $79"], correct: 2 },
                    { question: "A $100 petty cash fund has cash of $13 and receipts of $84. The journal entry to replenish the account would include a credit to", options: ["Cash for $87", "Petty Cash for $87", "Cash for $84", "Cash Over and Short for $3"], correct: 0 },
                    { question: "In preparing its bank reconciliation for the month of April 2012, Haskins, Inc. has available the following information:\n\nBalance per bank statement, 4/30/12 $27,280\nNSF check returned with 4/30/12 bank statement $900\nDeposits in transit, 4/30/12 $7,000\nBank service charges for April $10,400 \nOutstanding checks, 4/30/12 $40\n\n*What should be the adjusted cash balance at April 30, 2012?*", options: ["$23,880", "$23,840", "$22,940", "$22,980"], correct: 0 },
                    { question: "Electric Sunset Company gathered the following reconciling information in preparing its July bank reconciliation:\n\nCash balance per books, 7/31 $5,500\nDeposits in transit  $300 \nNotes receivable and interest collected by bank $1,100 \nBank charge for check printing $20 \nOutstanding checks $2,000 \nNSF check $170 \n\n*The adjusted cash balance per books on July 31 is*", options: ["$4,410", "$6,710", "$4,710", "$6,410"], correct: 3 },
                    { question: "If the month-end bank statement shows a balance of $36,000, outstanding checks are $10,000, a deposit of $4,000 was in transit at month end, and a check for $600 was erroneously charged by the bank against the account, the correct balance in the bank account at month end is", options: ["30,000", "$41,400", "$30,600", "$29,400"], correct: 2 },
                    { question: "if a check correctly written and paid by the bank for $418 is incorrectly recorded on the company's books for $481, the appropriate treatment on the bank reconciliation would be to  ", options: ["add $63 to the book's balance.", "deduct $418 from the book's balance.", "add $63 to the bank's balance.", "deduct $63 from the bank's balance."], correct: 0 },
                    { question: "In the month of May, Kijak Company Inc. wrote checks in the amount of $28,000. In June, checks in the amount of $38,000 were written. In May, $25,000 of these checks were presented to the bank for payment, and $33,000 in June. What is the amount of outstanding checks at the end of May?", options: ["$3,000", "$10,000", "$5,000", "$8,000"], correct: 0 },
                    { question: "A petty cash fund of $100 is replenished when the fund contains $4 in cash and receipts for $94. The entry to replenish the fund would  ", options: ["credit Cash Over and Short for $2", "debit Cash Over and Short for $2", "credit Miscellaneous Revenue for $2", "debit Miscellaneous Expense for $2"], correct: 1 },
                    { question: "Deposits in transit  ", options: ["are checks from customers which have not yet been received by the company.", "have not been recorded by the bank or the company.", "have been recorded on the company's books but not yet by the bank.", "have been recorded by the bank but not yet by the company."], correct: 2 }
                ]
            },
            {
                id: "ch8",
                title: "Ch 8: Receivables",
                description: "Bad debts and allowance methods.",
                questions: [
                    { question: "An aging of a company's accounts receivable indicates that $10,000 are estimated to be uncollectible. If Allowance for Doubtful Accounts has a $1,100 credit balance, the adjustment to record bad debts for the period will require a", options: ["debit to Bad Debts Expense for $10,000.", "debit to Allowance for Doubtful Accounts for $8,900.", "debit to Bad Debts Expense for $8,900.", "credit to Allowance for Doubtful Accounts for $10,000"], correct: 2 },
                    { question: "Using the percentage of receivables method for recording bad debts expense, estimated uncollectible accounts are $11,000. If the balance of the Allowance for Doubtful Accounts is $2,000 credit before adjustment, what is the amount of bad debts expense for that period?", options: ["$2,000", "$9,000", "$11,000", "$13,000"], correct: 1 },
                    { question: "A company has net credit sales of $950,000 for the year and it estimates that uncollectible accounts will be 2% of sales. If Allowance for Doubtful Accounts has a credit balance of $2,000 prior to adjustment, its balance after adjustment will be a credit of", options: ["$17,000", "$19,000", "$19,040", "$21,000"], correct: 3 },
                    { question: "Sakhr Company has *a debit balance of $5,000* in its Allowance for Doubtful Accounts before any adjustments are made at the end of the year. Based on review and aging of its accounts receivable at the end of the year, Sakhr estimates that $60,000 of its receivables are uncollectible. The amount of bad debts expense which should be reported for the year is", options: ["$5,000", "$55,000", "$60,000", "$65,000"], correct: 3 },
                    { question: "An aging of a company's accounts receivable indicates that $4,000 are estimated to be uncollectible. If Allowance for Doubtful Accounts has a $900 credit balance, the adjustment to record bad debts for the period will require a\n", options: ["debit to Bad Debts Expense for $4,000.", "debit to Allowance for Doubtful Accounts for $3,100.", "debit to Bad Debts Expense for $3,100.", "credit to Allowance for Doubtful Accounts for $4,000."], correct: 2 },
                    { question: "Sakhr Company has *a debit balance of $5,000* in its Allowance for Doubtful Accounts before any adjustments are made at the end of the year. Based on review and aging of its accounts receivable at the end of the year, Sakhr estimates that $60,000 of its receivables are uncollectible. The *ending balance* of allowance for doubtful account *after adjustment* is", options: ["$5,000", "$55,000", "$60,000", "$65,000"], correct: 2 },
                    { question: "An aging of a company's accounts receivable indicates that $3,000 are estimated to be uncollectible. If Allowance for Doubtful Accounts has a $700 debit balance, the adjustment to record bad debts for the period will require a", options: ["debit to Bad Debts Expense for $2,300.", " debit to Bad Debts Expense for $3,000.", "debit to Bad Debts Expense for $3,700.", "credit to Allowance for Doubtful Accounts for $700."], correct: 2 },
                    { question: "On October 1, 2012, Milago Company sells (factors) $500,000 of receivables to Beanfield Factors, Inc. Beanfield assesses a service charge of 3% of the amount of receivable ssold. The journal entry to record the sale by Milago will include", options: ["a debit of $500,000 to Accounts Receivable.", "a credit of $515,000 to Cash.", "a debit of $515,000 to Cash.", "a debit of $15,000 to Service Charge Expense."], correct: 3 },
                    { question: "XYZ Company accepted a national credit card for a $3,000 purchase. The cost of the goods sold is $1,800. The credit card company charges a 3% fee. What is the impact of this transaction on net operating income?", options: ["Increase by $1,110", "Increase by $1,164", "Increase by $1,200", "Increase by $2,910"], correct: 0 },
                    { question: "The Allowance for Doubtful Accounts account has a year-end credit balance, prior to adjustment, of $450. The bad debts are estimated at 3% of $650,000, the net credit sales. After the appropriate adjusting entry for bad debts, the Allowance for Doubtful Accounts should have a credit balance of", options: ["$19,500", "$19,950", "$19,050", "$20,400"], correct: 1 },
                    { question: "A company estimates that $20,000 of its $500,000 of accounts receivable will be uncollectible. Its Allowance for Doubtful Accounts presently has a credit balance of $18,000. The adjusting entry will include a ____________________ to Bad Debts Expense.", options: ["debit of $2,000", "credit of $2,000", "debit of $38,000", "credit of $38,000"], correct: 0 },
                    { question: "The company has a beginning credit balance of $530 in its Allowance for Doubtful Accounts. Over the course of the year, the company makes sales on account amounting to $120,000. By year-end, the company has total Accounts Receivable of $90,000. The company estimates that 6% of the total Accounts Receivable will not be collectible.\n\n*Calculate the estimated Bad Debts Expense for the year.*", options: ["$5,000", "$5,400", "$6,000", "$7,200"], correct: 0 },
                    { question: "The company has a beginning credit balance of $530 in its Allowance for Doubtful Accounts. Over the course of the year, the company makes sales on account amounting to $120,000. By year-end, the company has total Accounts Receivable of $90,000. The company estimates that 6% of the total Accounts Receivable will not be collectible.\n\n*What is the ending balance of the Allowance for Doubtful Accounts after the adjustment for Bad Debt Expense?*", options: ["$5,500", "$6,000", "$5,930", "$6,500"], correct: 1 }
                ]
            }
        ]
    },
    "managerial": {
        isChapters: true,
        chapters: [
            {
                id: "man1",
                title: "Managerial Accounting Exam",
                description: "Comprehensive Exam.",
                questions: [
                    { question: "The formula to determine the cost of goods manufactured is", options: ["Beginning raw materials inventory + Total manufacturing costs - Ending work in process inventory", "Beginning work in process inventory + Total manufacturing costs - Ending finished goods inventory", "Beginning finished good inventory + Total manufacturing costs - Ending finished goods inventory", "Beginning work in process inventory + Total manufacturing costs - Ending work in process inventory"], correct: 3 },
                    { question: "Which of the following costs would a computer manufacturer include in manufacturing overhead?", options: ["The cost of the disk drives.", "The wages earned by computer assemblers.", "The cost of the memory chips.", "Depreciation on testing equipment."], correct: 3 },
                    { question: "A cost of goods manufactured schedule shows beginning and ending inventories for", options: ["raw materials and work in process only", "work in process only", "raw materials only", "raw materials, work in process, and finished goods"], correct: 1 },
                    { question: "Which of the following managerial accounting techniques attempts to allocate manufacturing overhead in a more meaningful fashion?", options: ["Just-in-time inventory", "Total quality management", "Balanced scorecard", "Activity-based costing"], correct: 3 },
                    { question: "For the year, Redder Company has cost of goods manufactured of $600,000, beginning finished goods inventory of $200,000, and ending finished goods inventory of $250,000. The cost of goods sold is:", options: ["$450,000", "$500,000", "$550,000", "$600,000"], correct: 2 },
                    { question: "Wasson Company reported the following year-end information: \n\nBeginning work in process inventory $35,000\nBeginning raw materials inventory $18,000\nEnding work in process inventory $38,000\nEnding raw materials inventory $15,000\nRaw materials purchased $560,000\nDirect labor $180,000\nManufacturing overhead $120,000\n\n*How much is Wasson's total cost of work in process for the year?*", options: ["$608,000", "$863,000", "$860,000", "$898,000"], correct: 3 },
                    { question: "The management of an organization performs several broad functions. They are", options: ["planning, directing, and selling", "planning, directing, and controlling", "planning, manufacturing, and controlling", "directing, manufacturing, and controlling"], correct: 1 },
                    { question: "Gammil Company has beginning and ending raw materials inventories of $96,000 and $120,000, respectively. If direct materials used were $440,000, what was the cost of raw materials purchased?", options: ["$440,000", "$470,000", "$416,000", "$464,000"], correct: 3 },
                    { question: "Edmiston Company reported the following year-end information: beginning work in process inventory, $80,000; cost of goods manufactured, $780,000; beginning finished goods inventory, $50,000; ending work in process inventory, $70,000; and ending finished goods inventory, $40,000. \n*How much is Edmiston’s cost of goods sold for the year?*", options: ["$780,000", "$790,000", "$770,000", "$800,000"], correct: 1 },
                    { question: "Walker Company reported the following year-end information: \n\nBeginning work in process inventory $46,000 \nBeginning raw materials inventory $24,000 \nEnding work in process inventory $50,000 \nEnding raw materials inventory $20,000 \nRaw materials purchased $830,000 \nDirect labor $240,000\nManufacturing overhead $100,000 \n\n*How much is Walker's cost of goods manufactured for the year?*", options: ["$834,000", "$1,174,000", "$1,170,000", "$1,178,000"], correct: 2 },
                    { question: "Barton Company has beginning work in process inventory of $144,000 and total manufacturing costs of $686,000. If cost of goods manufactured is $640,000, what is the *cost of the ending work in process inventory*?", options: ["$170,000", "$198,000", "$210,000", "$190,000"], correct: 3 },
                    { question: "Managerial accounting:", options: ["is governed by generally accepted accounting", "places emphasis on special-purpose information", "pertains to the entity as a whole and is highly", "is limited to cost data"], correct: 1 },
                    { question: "After passage of the Sarbanes-Oxley Act:", options: ["reports prepared by managerial accountants must by audited by CPAs", "CEOs and CFOs must certify that financial statements give a fair presentation of the company’s operating results", "the audit committee, rather than top management, is responsible for the company’s financial statements", "reports prepared by managerial accountants must comply with generally accepted accounting principles (GAAP)"], correct: 1 },
                    { question: "Ogleby Inc.'s accounting records reflect the following inventories: \n\n*Dec 31 2012:*\nRaw materials inventory $120,000 \nWork in process inventory $156,000\nFinished goods inventory $150,000 \n\n*Dec 31 2013:*\nRaw materials inventory $96,000 \nWork in process inventory $174,000\nFinished goods inventory $138,000 \n\nDuring 2013, Ogleby purchased $840,000 of raw materials, incurred direct labor costs of $150,000, and incurred manufacturing overhead totaling $192,000. \n\nHow much would Ogleby Manufacturing report as cost of goods manufactured for 2013?", options: ["$1,164,000", "$1,224,000", "$1,218,000", "$1,188,000"], correct: 0 },
                    { question: "Indirect labor is a:", options: ["non-manufacturing cost", "raw material cost", "product cost", "period cost"], correct: 2 },
                    { question: "Assuming that the direct materials used is $1,400,000, compute the total manufacturing costs using the following information:\n\n*Note:* thousands values is brief\n\nRaw materials inventory, 1/1 $20k\nRaw materials inventory, 31/12 $40k\nWork in process, 1/1 $18k\nWork in process, 31/12 $12k\nFinished goods, 1/1 $40k\nFinished goods, 31/12 $32k\nRaw materials purchases $1,400k\nDirect labor $560k\nFactory utilities $1,500k\nIndirect labor $50k\nFactory depreciation $400k\nOperating expenses $420k", options: ["$2,560k", "$2,554k", "$2,360k", "$2,980k"], correct: 1 },
                    { question: "Which of the following is not an element of manufacturing overhead?", options: ["Sales manager’s salary", "Plant manager’s salary", "Factory repairman’s wages", "Product inspector’s salary"], correct: 0 },
                    { question: "Which of the following costs are classified as a period cost?", options: ["Wages paid to a factory custodian", "Wages paid to a production department supervisor", "Wages paid to a cost accounting department supervisor", "Wages paid to an assembly worker"], correct: 2 },
                    { question: "Molina Company has beginning and ending work in process inventories of $130,000 and $145,000 respectively. If total manufacturing costs are $650,000, what is the total *cost of goods manufactured*?", options: ["$870,000", "$780,000", "$635,000", "$665,000"], correct: 2 }
                ]
            }
        ]
    },
    "cost": {
        isChapters: true,
        chapters: [
            {
                id: "cost1",
                title: "Part 1: Manufacturing Costs",
                description: "Cost of goods manufactured & sold calculations.",
                questions: [
                    { question: "The following information pertains to Jordan Corporation:\n\nBeginning work-in-process inventory $50,000 \nEnding work-in-process inventory 48,000 \nBeginning finished goods inventory 180,000 \nEnding finished goods inventory 195,000 \nCost of goods manufactured 1,220,000 \n\n*What is cost of goods sold?*", options: ["$1,235,000", "$1,205,000 ", "$1,218,000", "$1,222,000"], correct: 1 },
                    { question: "The following information pertains to Jordan Corporation: \n\nBeginning finished goods,1/1/2019 $90,000 \nEnding finished goods, 12/31/2019 77,000 \nCost of goods sold 270,000 \nSales revenue 500,000 \nOperating expenses 155,000 \n\n*What is cost of manufactured for 2019?*", options: ["$230,000", "$257,000", "$283,000", "$355,000"], correct: 1 },
                    { question: "The following information pertains to Jordan Corporation: \n\nBeginning finished goods, 1/1/2019 $90,000 \nEnding finished goods, 12/31/2019 77,000 \nCost of goods sold 270,000 \nSales revenue 500,000 \nOperating expenses 155,000\n \n*What is gross margin for 2019?*", options: ["$283,000", "$355,000", "$230,000", "$257,000"], correct: 2 },
                    { question: "The following information pertains to Jordan Corporation: \n\nBeginning finished goods, 1/1/2019 $90,000 \nEnding finished goods, 12/31/2019 77,000 \nCost of goods sold 270,000 \nSales revenue 500,000 \nOperating expenses 155,000 \n\n*What is operating income for 2019?*", options: ["$75,000", "$112,000", "$62,000", "$230,000"], correct: 0 },
                    { question: "Answer the following questions *from this to last question* by using the information below for to Hanin Corporation:\n\nSandpaper $6,000 ,Materials-handling costs 210,000 ,Lubricants and coolants 15,000 ,Miscellaneous indirect manufacturing labor 120,000 ,Direct manufacturing labor 900,000 ,Direct materials inventory, Jan. 1, 2018 120,000 ,Direct materials inventory, Dec. 31, 2018 150,000 ,Finished-goods inventory, Jan. 1, 2018 300,000 ,Finished-goods inventory, Dec. 31, 2018 450,000 ,Work-in-process inventory, Jan. 1,2018 30,000 ,Work-in-progress inventory, Dec. 31, 2018 42,000 ,Plant-leasing costs 162,000 ,Depreciation plant equipment 108,000 ,Property taxes on plant equipment 12,000 ,Fire insurance on plant equipment 9,000 ,Direct materials purchased 1,380,000 ,Revenues 4,080,000 ,Marketing promotions 180,000 ,Marketing salaries 300,000 ,Distribution costs 210,000 ,Customer-service costs 300,000\n\nWhat is *direct material used* for 2018?", options: ["$1,350,000", "$1,500,000", "$1,600,000", "$1,450,000"], correct: 0 },
                    { question: "By using the informations before , What is *Manufacturing costs incurred* during 2018?", options: ["$2,891,000", "$1,892,000", "$2,982,000", "$2,892,000"], correct: 3 },
                    { question: "What is *Cost of goods manufactured* during 2018?", options: ["$2,808,000", "$1,892,000", "$2,880,000", "$2,892,000"], correct: 2 },
                    { question: "What is *Cost of goods sold* during 2018?", options: ["$2,730,000", "$2,630,000", "$2,530,000", "$3,180,000"], correct: 0 },
                    { question: "What is *Opreating income* during 2018?", options: ["$1,350,000", "$360,000", "$990,000", "$1,350,000"], correct: 2 }
                ]
            },
            {
                id: "cost2",
                title: "Part 2: Job Order Costing",
                description: "Journal entries and unit costs.",
                questions: [
                    { question: "O'Reilly Enterprises manufactures digital video equipment. \n\nFor each unit $2,950 of direct material is used and there is $2,000 of direct manufacturing labor at $20 per hour.\nManufacturing overhead is applied at $35 per direct manufacturing labor hour.\n\n  *Calculate the cost of each unit.*", options: ["$4,950", "$9,950 ", "$8,450", "$11,950"], correct: 2 },
                    { question: "What is the appropriate *journal entry* if $100,000 of materials were purchased on account for the month of August?", options: ["Dr. Materials Control $100,000\n  Cr. Account Payable Control $100,000", "Dr. Work-in-Process Control $100,000 \n  Cr. Accounts Payable Control \n$100,000 ", "Dr. Manufacturing Overhead Control $100,000 \n  Cr. Accounts Receivable Control $100,000", "Dr. Manufacturing Allocated $100,000 \n  Cr. Accounts Receivable Control $100,000"], correct: 0 },
                    { question: "What is the appropriate *journal entry* if direct materials of $20,000 and indirect materials of $3,000 are sent to the manufacturing plant floor?", options: ["Dr. Work-in-Process Control $20,000\n  Cr. Materials Control $20,000", "Dr. Work-in-Process Control $23,000\n  Cr. Materials Control $23,000", "Dr. ManufacturingOverhead Control $3,000 \nDr. Materials Control $20,000 \n  Cr. Work-in-Process Control $23,000 \n", "Dr. Work-in-Process Control $20,000\nDr. Manufacturing Overhead Control $3,000 \n  Cr. Materials Control $23,000"], correct: 3 },
                    { question: "What would be the appropriate *journal entry* if the following labor wages were incurred in a furniture manufacturing company? \n\n  Assembly workers $20,000\n  Janitors $10,000", options: ["Dr. Work-in-Process Control $30,000 \n  Cr. Wages Payable Control $30,000 ", "Dr. Work-in-Process Control $20,000 \nDr. Manufacturing Overhead Control $10,000 \n  Cr. Wages Payable Control $30,000 ", "Dr. Manufacturing Overhead Control $30,000 \n  Cr. Wages Payable Control $30,000", "Dr. Wages Payable Control $30,000 \n  Cr. Work-in-Process Control $30,000"], correct: 1 },
                    { question: "Manufacturing overhead costs incurred for the month are: \n\nUtilities $30,000 \nDepreciation on equipment $25,000 \nRepairs $20,000 \n\n  *Which is the correct journal entry assuming utilities and repairs were on account?*", options: ["Dr. Manufacturing Overhead Control 75,000 \n  Cr. Accounts Payable Control $50,000\n  Cr. Accumulated Depreciation Control $25,000", "Dr. Manufacturing Overhead Control $75,000 \n  Cr. Accounts Payable Control $75,000", "Dr. Manufacturing Overhead Control $75,000 \n  Cr. Accumulated Depreciation Control $75,000 ", "Dr. Accumulated Depreciation Control $25,000 \nDr. Accounts Payable Control $50,000 \n  Cr. Manufacturing Overhead Control $75,000"], correct: 0 },
                    { question: "The journal entry to record the materials placed into production would include a:", options: ["credit to Direct Materials Inventory for $82,000", "debit to Direct Materials Inventory for $148,000", "credit to WIP Inventory for $82,000", "debit to WIP Inventory for $148,000"], correct: 3 },
                    { question: "The ending balance of *direct materials* inventory is:", options: ["$92,000", "$174,000", "$82,000", "$108,000"], correct: 0 },
                    { question: "The ending balance of *work-in-process* inventory is:", options: ["$438,500", "$146,500", "$130,000", "$422,000"], correct: 0 },
                    { question: "The ending balance of *finished goods* inventory is:", options: ["$58,000", "$36,000", "$94,000", "$292,000"], correct: 0 }
                ]
            }
        ]
    },
    "financial": {
        isChapters: true,
        chapters: [
            {
                id: "fin1",
                title: "الودائع والحسابات (Deposits)",
                description: "القيود المحاسبية للودائع والفوائد.",
                questions: [
                    { question: "اودع العميل فادي مبلغ 5000 دينار في بنك القاهرة عمان كوديعة لأجل أو يمكن القول كوديعة لأشعار", options: ["5000 من ح/ الخزينة \n  5000 الى ح/ الودائع لأجل أو بإشعار ", "5000 من ح/ الخزينة \n  5000 الى ح/ الحسابات الجارية الدائنة ", "5000 من ح/ الودائع لاجل أو باشعار \n  5000 الى ح/ الخزينة ", "غير ذلك"], correct: 0 },
                    { question: "قام العميل هادي بتحويل مبلغ 3000 دينار من حسابه الجاري الدائن الى حساب الوديعة لأجل أو يمكن القول لإشعار", options: ["3000 من ح/ الخزينة \n  3000 الى ح/ الودائع لأجل أو بإشعار ", "3000 من ح/ الخزينة \n  3000 الى ح/ الحسابات الجارية الدائنة ", "3000 من ح/ الحسابات الجارية الدائنة\n  3000 ح/ الودائع لأجل او بإشعار", "غير ذلك"], correct: 2 },
                    { question: "أودع العميل مصطفى بإيداع شيك قيمته 4500 دينار في حساب الوديعة (لأجل أو بإشعار) والموجود في بنك الاردن علما بان الشيك مسحوب على بنك الاردني الكويتي", options: ["4500 من ح/ شيكات برسم التحصيل\n  4500 الى ح/ الودائع لأجل أو بإشعار ", "4500 من ح/ الخزينة \n  4500 الى ح/ الودائع لأجل أو بإشعار ", "4500 من ح/ الحسابات الجارية الدائنة \n  4500 الى ح/ الودائع لأجل أو بإشعار ", "غير ذلك"], correct: 0 },
                    { question: "بتاريخ 2018/1/1 قام العميل عبدالرحمن بربط وديعة لأجل تسعة شهور بقيمة 10000 دينار في حساب وديعة (لأجل او بإشعار) في بنك الاردن وبفائدة %4 سنويا، وقد كانت سياسة البنك احتساب الفوائد المستحقة على حساب الوديعة بشكل شهري، المطلوب تحديد قيمة الفائدة المدينة للشهر الاول ", options: ["400 من ح/ الفوائد المدينة للودائع (لأجل او بإشعار)\n  400 الى ح/ الفوائد المستحقة غير المدفوعة للودائع (لأجل او بإشعار)", "3.33 من ح/ الفوائد المدينة للودائع (الأجل او بإشعار)\n  33.3 الى ح/ الفوائد المستحقة غير المدفوعة للودائع (لأجل او بإشعار)", "300 من ح/ الفوائد المدينة للودائع (لأجل او بإشعار)\n  300 الى ح/ الفوائد المستحقة غير المدفوعة للودائع (لأجل او بإشعار)", "غير ذلك"], correct: 1 },
                    { question: "بتاريخ 2018/1/1 قام العميل عاصي بربط وديعة لأجل تسعة شهور بقيمة 10000 دينار في حساب وديعة (لأجل او بإشعار) في بنك لبنان والمهجر وبفائدة 5% سنويا، وقد كانت سياسة البنك احتساب الفوائد المستحقة على حساب الوديعة بشكل شهري، وفي نهاية المدة (تاريخ استحقاق) قام البنك يإضافة الفائدة على الحساب الجاري العميل، المطلوب تحديد قيمة الفائدة المستحقة على حساب الوديعة مع تحميلها للحساب", options: ["375 من ح/ الفوائد المستحقة غير المدفوعة للودائع (لأجل أو بإشعار) \n  375 الى ح/ الحسابات الجارية الدائنة", "125 من ح/ الفوائد المستحقة غير المدفوعة للودائع (الأجل أو بإشعار) \n  125 الى ح/ الحسابات الجارية الدائنة", "500 من ح/ الفوائد المستحقة غير المدفوعة للودائع (الأجل أو بإشعار) \n  500 الى ح/ الحسابات الجارية الدائنة", "غير ذلك "], correct: 0 },
                    { question: "بتاريخ 2018/11/15 استحق العميل \nخالد الوديعة لأجل قيمتها 20000 دينار وسحبها نقدا", options: ["20000 من ح/ الودائع لأجل أو بإشعار\n  20000 الى ح/ الحساب الجاري المدين", "20000 من ح/ الودائع لأجل أو بإشعار\n  20000 الى ح/ الحساب الجاري الدائن", "20000 من ح/ الودائع لأجل أو بإشعار\n  20000 الى ح/ الخزينة", "غير ذلك"], correct: 2 },
                    { question: "أودع العميل شادي مبلغ 5000 دينار في بنك القاهرة عمان كوديعة في صندوق التوفير", options: ["5000 من ح/ الحسابات الجارية الدائنة\n  5000 الى ح/ ودائع التوفير ", "5000 من ح/ الخزينة \n  5000 الى ح/ ودائع التوفير", "5000 من ح/ شيكات برسم التحصيل \n  5000 الى ح/ ودائع التوفير", "غير ذلك"], correct: 1 },
                    { question: "يوجد لدى العميل سامي حساب توفير (ودائع التوفير) في بنك العربي وقد استحق العميل سامي فائدة قيمتها 300 على الشهر الأول لحساب الوديعة ولم تسدد للعميل وانما تم الاحتفاظ بها في حساب الفوائد المدينة المستحقة والغير المسددة", options: ["300 من ح/ الخزينة \n  300 الى ح/ فوائد المدينة المستحقة غير المدفوعة لودائع التوفير", "300 من ح/ الفوائد المدينة لصندوق التوفير \n  300 الى ح/ فوائد المدينة المستحقة غير المدفوعة لودائع التوفير", "300 من ح/ الفوائد الدائنة لصندوق التوفير \n  300 الى ح/ فوائد المدينة المستحقة غير المدفوعة لودائع التوفير", "غير ذلك"], correct: 1 },
                    { question: "بتاريخ 2018/5/1 استحق العميل فائدة على حساب ودائع التوفير وقيمتها 500 دينار تم تحميلها الى حسابه الجاري الدائن والموجود لدى نفس(بنك ABC)", options: ["500 من ح/ فوائد الدائنة المستحقة غير المدفوعة لودائع التوفير \n  500 الى ح/ الحسابات الجارية الدائنة", "500 من ح/ فوائد المدينة المستحقة غير المدفوعة لودائع التوفير \n  500 الى ح/ الحسابات الجارية الدائنة", "500 من ح/ فوائد المدينة المدفوعة لودائع التوفير \n  500 الى ح/ الحسابات الجارية الدائنة", "غير ذلك"], correct: 0 },
                    { question: "بتاريخ 2018/2/5 قام العميل اياد بشراء شهادات إيداع بقيمة 9000 دينار من بنك الإسكان وتمت عملية الدفع من خلال حسابه الجاري الدائن الموجود في نفس البنك", options: ["9000 من ح/ الخزينة \n 9000 الى ح/ شهادات الإيداع-اياد", "9000 من ح/ الحسابات الجارية المدينة-اياد\n  9000 الى ح/ شهادات الإيداع-اياد", "9000 من ح/ الحسابات الجارية الدائنة-اياد \n  9000 الى ح/ شهادات الإيداع-اياد", "غير ذلك"], correct: 2 }
                ]
            }
        ]
    }
};

